name: Check Updates

on:
  schedule:
    - cron: 30 * * * *
  workflow_dispatch:
    inputs:
      force:
        description: Force decompile latest version
        type: boolean
        default: false

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check.outputs.id }}
    steps:
      - name: Check Minecraft updates
        id: check
        uses: IotaBread/minecraft-update-check-action@v0
        with:
          version-manifest-url: https://piston-meta.mojang.com/mc/game/version_manifest_v2.json
          cache-base-key: mc-version-

  decompile:
    needs: check
    if: ${{ needs.check.outputs.version != '' || inputs.force }}
    uses: ./.github/workflows/decompile.yml
    with:
      version: ${{ needs.check.outputs.version }}
      commit: true
    permissions:
      contents: write
